version: '3.8'

services:
  notes-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      # The connection URL is now built from variables defined in the .env file
      POSTGRES_URL: ${POSTGRES_URL}
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      # These values are pulled from the .env file
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      # The host port is now configurable via the .env file
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: